server:
  port: 8761

spring:
  application:
    name: discoveryservice

  config:
    import: optional:configserver:http://localhost:8888 # 구성정보 설정
  cloud:
    config:
      name: ecommerce # yml 파일명 앞부분

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

