server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: /Users/chany/Study/Git/Today-I-Learned/MSA/config-repo
          uri: https://github.com/inshakr2/spring-config-repo
